version: '3.8'

services:
  qr_code_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QR_CODE_DIR=/app/qr_codes
      - FILL_COLOR=black
      - BACK_COLOR=white
    volumes:
      - ./qr_codes:/app/qr_codes  # Maps the local 'qr_codes' directory to '/app/qr_codes' in the container
    command: --url https://hub.docker.com/r/varuns03/is601-assignment-7-qr_code_docker  # Replace 'main.py' with your script's filename if different
